### 예제 1
1부터 100 사이에서 40개의 서로 다른 정수를 임의로 선택하여 저장하자.

In [8]:
import numpy as np
rg = np.arange(1, 100)
vec = np.random.choice(rg, 40, replace=False)
print(vec)

[74 50 72 97 85 59 93 12 55 69 88 31 25 58 19 70 99  3 22  6 65 47  4 26
 56 40 75 81 87 41 34 11 37 38  7 44 86 53 32 45]


**1-1) 만들어진 벡터를 사용하여 5행 8열의 행렬을 생성하시오**

In [10]:
new_set = vec.reshape(5, 8)
print(new_set)

[[74 50 72 97 85 59 93 12]
 [55 69 88 31 25 58 19 70]
 [99  3 22  6 65 47  4 26]
 [56 40 75 81 87 41 34 11]
 [37 38  7 44 86 53 32 45]]


**1-2) 예제 1에서 생성된 행렬에서 2행과 3행만을 추출하여 저장하시오**

In [13]:
extracted = new_set[1:3, :]
print(extracted)

[[55 69 88 31 25 58 19 70]
 [99  3 22  6 65 47  4 26]]


**1-3) 예제 1에서 생성된 행렬에서 (1, 4, 7, 8)열을 추출하여 저장하시오.**

In [39]:
extracted2 = new_set[:, [0,3,6,7]]
print(extracted2)

[[74 97 93 12]
 [55 31 19 70]
 [99  6  4 26]
 [56 81 34 11]
 [37 44 32 45]]


**1-4) 예제 1에서 생성된 행렬의 7번째 열의 평균과 분산을 구하시오** 

In [44]:
sevenths = new_set[:, [6]]
    
print("평균", np.mean(sevenths))
print("분산", np.var(sevenths))

평균 36.4
분산 916.24


### 예제 2
1부터 20 사이에서 1개의 숫자를 임의로 선택하여 저장하자. 이 숫자가 10 이상이면 "P"를 출력하고 10 미만이면 "NP"를 출력하는 코드를 작성해보시오.

In [46]:
n = np.random.randint(1, 20, 1)[0]

if (n >= 10):
    print("P")
else:
    print("NP")

P


### 예제 3
1부터 20 사이에서 8개의 숫자를 임의로 선택하여 저장하자. 8개의 숫자들 각각에 대해 숫자가 10 이상이면 "P"를 출력하고 10 미만이면 "NP"를 출력하는 코드를 작성해보시오.

In [47]:
def isBigger(n):
    if (n >= 10):
        return "P"
    else:
        return "NP"

nums = np.random.randint(1, 20, 8)

for n in nums:
    print( isBigger(n) )

NP
P
NP
P
P
NP
P
NP
