## 3.1. 벡터와 행렬

### 3.1.1. 벡터

- `full(size, value)`: value가 size개 들어있는 integer 벡터
- `zeros(size, dtype = float)`: 0이 size개 들어있는 float 벡터
- `ones(size, dtype = float)`: 1이 size개 들어있는 float 벡터

In [2]:
import numpy as np

a1 = np.full(6, 0) # integer
a2 = np.zeros(6) # default float
a3 = np.zeros(6, dtype = int) # integer

print(a1)
print(a2)
print(a3)

[0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0]


In [3]:
b1 = np.full(6, 1) # 개수, 값
b2 = np.ones(6)    # 개수만 parameter로 받음. method 자체가 값 지정.
b3 = np.ones(6, dtype = int)

print(b1)
print(b2)
print(b3)

[1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1]


**np.arrange**

- 

In [4]:
c1 = np.arange(6) # arange(k): 0 ~ k-1까지 정수
c2 = np.arange(2, 7) # arange(m, n): m ~ n-1까지 정수
c3 = np.arange(3, 17, 3) # arange(m, n, d): m~ n-1까지 d간격으로

print(c1)
print(c2)
print(c3)

[0 1 2 3 4 5]
[2 3 4 5 6]
[ 3  6  9 12 15]


**np.random**

- `rand(k)`: 0~1에서 k개 난수 생성
- `randn(k)`: 표준정규분포에서 k개 난수 생성
- `choice(a, size=k, replace=True)`: a에서 k개를 반복을 허용해서 선택
- `randint(a, b, k)`: a ~ b-1 사이 정수에서 k개 선택

In [5]:
print(np.random.rand(5)) # 0~1 난수 생성
print(np.random.randn(5)) # 표준정규분포에서 난수 생성

[0.20890368 0.44057877 0.41841429 0.38848835 0.4747189 ]
[-0.701235   -0.67073294 -1.19574611  1.13029393 -0.07400332]


In [6]:
# random.choice
print( np.random.choice(np.arange(10), size=5) )
print( np.random.randint(0, 10, 5) )

[2 9 6 5 8]
[0 3 5 5 3]


### 3.1.2. 행렬

**np.array( list )**

- `type(array)`: numpy.ndarray
- `array.shape`: array의 (행, 열)
- 값에 접근할 때는 `array[x, y]` 형태로

In [7]:
# 1차원
a = np.array( [1, 2, 3] )

print( type(a) )
print( a.shape )
print( a[0], a[1], a[2] )

a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [8]:
# 2차원
b = np.array( [[1,2,3],[4,5,6]] )

print(type(b))
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

<class 'numpy.ndarray'>
(2, 3)
1 2 4


size가 들어갔던 자리에 (xsize, ysize)를 넣어서 2차원으로 할 수 있음

- `zeros( (xsize, ysize) )`
- `ones( (xsize, ysize) )`
- `full( (xsize, ysize), value )`
- `random.rand( (k1, k2) )`

추가

- `np.eye(r, c=None, k=0)`: An array (r rows) where all elements are equal to 0, except for the k-th diagonal, whose values are equal to 1.

In [9]:
# 위에서 배운 애들 2차원으로 해보자
a = np.zeros((2, 2))
print(a, a.dtype)

b = np.ones((1,2))
print(b)

c = np.full((2,2), 7)
print(c, c.dtype)

d = np.random.rand(2,2)
print(d)

# 새로운 것도 있다
e = np.eye(3)
print(e)

[[0. 0.]
 [0. 0.]] float64
[[1. 1.]]
[[7 7]
 [7 7]] int64
[[0.70934788 0.7361672 ]
 [0.81971194 0.52327322]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
a = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )
print(a)
print("\n")

b = np.arange(1, 13)
print(b)
print("\n")

b = b.reshape(3, 4)
print(b)
print("\n")

c = a[1:2, 0:3]
print(c)
print("\n")

c[0, 0] = 77
print(c)
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[5 6 7]]


[[77  6  7]]
2


- `a[[0,0,1,1], [1,2,1,2]]`: a에서 `a[0, 1], a[0, 2], a[1, 1], a[1, 2]`를 저장한 셈

In [99]:
a = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )
print(a)
print("\n")

c = a[[0,0,1,1], [1,2,1,2]]
print(c)
print("\n")

c = c.reshape(2, 2)
print(c)
print("\n")

c[0,0] = 77
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[2 3 6 7]


[[2 3]
 [6 7]]


2


**boolean expression about an array**

- `array > n`: returns boolean array 
- `array[array > n]` == `array[a > n]`: returns array only with elements that is true

In [57]:
a = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )

print(a)
print("\n")

bool_idx = (a > 5)

print(bool_idx)
print("\n")
print(a[bool_idx])
print(a[a>5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


[ 6  7  8  9 10 11 12]
[ 6  7  8  9 10 11 12]


## 3.2. 기본 함수

**배열 연산**

In [17]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))

print(np.dot(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [49]:
x = np.array([[1, 2], [3, 4]])

print( np.sum(x) )
print( np.sum(x, axis=0) )
print( np.sum(x, axis=1) )

print( np.mean(x) )
print( np.mean(x, axis=0) )
print( np.mean(x, axis=1) )

print( np.var(x) )
print( np.var(x, axis=0) )
print( np.var(x, axis=1) )

10
[4 6]
[3 7]
2.5
[2. 3.]
[1.5 3.5]
1.25
[1. 1.]
[0.25 0.25]


In [15]:
a = -3
b = 2.6

print(np.abs(a))
print(np.round(b), np.floor(b), np.ceil(b))

3
3.0 2.0 3.0


In [53]:
import math

a = np.exp(1)
print(a, math.e)
print(np.log(a), math.log(a), math.log(a, 10))
print(np.sin(np.pi/2), math.sin(math.pi/2))

2.718281828459045 2.718281828459045
1.0 1.0 0.43429448190325176
1.0 1.0


In [55]:
from scipy.special import comb
from scipy.special import factorial

print(factorial(5, exact=True)) # 5!
print(comb(10, 3, exact=True)) # 10 C 3
print(comb(10, 3, exact=True, repetition=True)) # 10 H 3 = 12 C 3
print(comb(12, 3, exact=True))


120
120
220
220


## 3.3. 조건문과 반복문

### 3.3.1. 조건문

**헷갈릴만한 것**

- `0`은 False
- `[False]`는 True

In [60]:
a = 1

if a == 1:
    print("a is %i" %a)

a is 1


In [65]:
b = 3

if b == 3:
    print('b = %i' %b)
else:
    print('b != %i' %b)

b = 3


In [67]:
a = 100

if a % 2 == 0:
    print('a is even')
else:
    print('a is odd')

if not a % 2: # 0은 false이므로
    print('a is even')
else:
    print('a is odd')

a is even
a is even


In [71]:
a = 101

if a % 2 == 0:
    print('a is divided by 2')
elif a % 3 == 0:
    print('a is divided by 3')
else:
    print('a is neither divided by 2 nor 3')


a is neither divided by 2 nor 3


In [20]:
if False:
    print("this is false")
    
if [False]:
    print("this is true")
    
if "zero":
    print("this is true")


this is true
this is true


### 3.3.2. 반복문

- `continue` forces the loop to start at the next iteration<br> => will jump back to the top of the loop
- `pass` means "there is no code to execute here" and will continue through the remainder or the loop body. continue will<br> => will continue processing

In [74]:
a = range(10)
print(a)

b = range(0, 10)
print(b)

c = range(-10, 0)
print(c)

range(0, 10)
range(0, 10)
range(-10, 0)


In [75]:
for i in range(1, 10):
    print(i)

1
2
3
4
5
6
7
8
9


In [83]:
seq = []
for i in range(1, 10):
    if i % 2 == 0:
        pass
    else:
        seq.append(i)
        
print(seq)

[1, 3, 5, 7, 9]


In [77]:
a = []

for i in range(1, 100):
    a.append(i)
    if sum(a) >= 100:
        print(sum(a))
        break
        
print(a)

105
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [78]:
a = []

i = 1
while len(a) < 10:
    a.append(i)
    i += 1

print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [79]:
'''
while True:
    print('무한루프에 주의합시다')
'''

"\nwhile True:\n    print('무한루프에 주의합시다')\n"

In [80]:
i = 0
while True:
    print('따라서 break를 적절히 사용해야 합니다')
    i += 1
    if (i > 5):
        break

따라서 break를 적절히 사용해야 합니다
따라서 break를 적절히 사용해야 합니다
따라서 break를 적절히 사용해야 합니다
따라서 break를 적절히 사용해야 합니다
따라서 break를 적절히 사용해야 합니다
따라서 break를 적절히 사용해야 합니다


In [30]:
a = []
i = 0
while len(a) < 5:
    i += 1
    if i%2 == 0: continue
    a.append(i)
print(a)

[1, 3, 5, 7, 9]


### 3.4. 사용자 정의 함수


In [87]:
def sum(a, b):
    return(a + b)

print(sum(1, 3))
print(sum('a', 'b')) # 주의

4
ab


**multiple return value 가능 (주의)**

In [86]:
def sum2(a, b):
    return a, b, a+b

value1, value2, value3 = sum2(10, 11)

print('%i + %i = %i' %(value1, value2, value3))

value = sum2(10, 11)
print(value)

10 + 11 = 21
(10, 11, 21)


**입력변수가 몇 개가 될지 모르는 경우 `*args` 사용**

In [55]:
def sum(*args):
    value = 0
    for i in args: value += i
    return value

a = sum(10, 11, 12, 13, 14)
print(a)

60


### 과제 복습

In [33]:
a = np.random.choice(np.arange(1, 100), size=40, replace=False)
print(a)

[ 4 32 44 10 82 80 41 17 97 50 51 98 56 25 19 31 94 43 77 70 12  1  9 85
 83 57 81 90 26 88 21 86  3 34 18 93  2 37 78 96]


In [35]:
b = a.reshape(5, 8)
b

array([[ 4, 32, 44, 10, 82, 80, 41, 17],
       [97, 50, 51, 98, 56, 25, 19, 31],
       [94, 43, 77, 70, 12,  1,  9, 85],
       [83, 57, 81, 90, 26, 88, 21, 86],
       [ 3, 34, 18, 93,  2, 37, 78, 96]])

In [54]:
c = b[1:3]
c[0, 0] = 999
b # 바뀜

array([[  4,  32,  44,  10,  82,  80,  41,  17],
       [999,  50,  51,  98,  56,  25,  19,  31],
       [ 94,  43,  77,  70,  12,   1,   9,  85],
       [ 83,  57,  81,  90,  26,  88,  21,  86],
       [  3,  34,  18,  93,   2,  37,  78,  96]])

In [51]:
d = b[:, [0, 3, 6, 7]]
d[0,0] = 999
b # 안바뀜

array([[ 4, 32, 44, 10, 82, 80, 41, 17],
       [97, 50, 51, 98, 56, 25, 19, 31],
       [94, 43, 77, 70, 12,  1,  9, 85],
       [83, 57, 81, 90, 26, 88, 21, 86],
       [ 3, 34, 18, 93,  2, 37, 78, 96]])

In [59]:
col7 = b[:, 6]
np.mean(col7)

33.6

In [64]:
def moreThan10(i):
    if i >= 10:
        print("P")
    else:
        print("NP")

r = np.random.randint(1, 20, 1)
print(r)
moreThan10(r)

[2]
NP


In [ ]:
def moreThan10(i):
    if i >= 10:
        print("P")
    else:
        print("NP")

arr = np.random.randint(1, 20, 8)

for i in range(len(arr)):
    print(arr[i])
    moreThan10(r)